### PR TITLE
feat: add support for global configuration

### PR DESCRIPTION
**Pull request by jreilly-lukava**
Adds support for global configuration options in package.json, .nxreleaserc, or nxrelease.config.js files as outlined in #10

### CODE REVIEW

**Comment by jreilly-lukava** [comment]
I thought about creating some tests, but I'm not sure how mock the cosmiconfig.  Maybe it should be retrieved more globally and then passed into resolveOptions and then we could mock easier.  Thoughts?

**Review by TheUnderScorer — COMMENTED** [review]
Looks good! One thing only - could you add at least one test, to make sure that we are using the global configuration correctly? 😁 

I was thinking of adding some global configuration to the test app repository, and then checking whether this configuration was used. But if you have any ideas for better approach, feel free to do that instead!

**Comment by jreilly-lukava** [comment]
I did some refactoring to make it more functional programming which is easier to test and added some unit tests to help ensure things are being merged together properly.

I still can't get the e2e tests to run on either my Mac or Windows box, the errors are different on each.  Should probably troubleshoot that at some point.

**Comment by TheUnderScorer** [comment]
Looks good, I'm going to release this, thanks!

BTW. Regarding e2e tests you are right :<. But for now I don't have time to take care of that, luckily we have the pipelines 😄.

**Pull request merged**
